language: go
sudo: false
go:
  - 1.x
install:
  - go get -u -v github.com/shadowsocks/v2ray-plugin
  - go get -u -t -v ./...
script:
  - go test
  - PATH=$PATH:$GOPATH/bin bash ./script/test.sh
deploy:
  provider: releases
  prerelease: true
  skip_cleanup: true
  file_glob: true
  file: bin/*
  on:
    repo: shadowsocks/go-shadowsocks2
    branch: master
    tags: true
  api_key:
    secure: hXN6BYAim9TYIf/NpI8CuaBQmIJ+q6asypw37DP+cBkdkXbmAX6oSPbQMKUVGQg3U7YNbebaXmCdu87ORiEmTzhAPf2rG86Q80Q1KcU8fpGgxQ+Ie2XmaRlkBnkT1QVym9e/4jCtnBg5B6iDu5//K94ASgKL8z3GLgzJ/+k4lOjxV2iRTrZwdvs30yy3QqSTpp2d8+JMkg3XFv5LiUqTo5xCLgavgRJ23UEAk1JsxgBVFnggEVywtdWKXdFX23CyQ/0rDTdegYXHOGMRSo/PXql8VMFwljc9fSOCjoKtKsmO/W61T2O/2OY/aOcyIdztEDoboZ6hfFt7hYsakLWhx6UoTH6k6PTwzTqsOjW+RofZVxGXG8sNmRi1bQBX3pDQaVTnzFZ7cuf9qclT3ATgISVTErF6fakXBTBja53IfdKOMgThPJNF7vThq1SFyhXnysmHKyHJq/4BM6OEb/Ac25ZhILU1FfwTcRjwi8w6iOGLU6vwcypuqctO9d5NbmNdkJ32YsbcDZoUaJxEUA+LiyaZYkjVyKWkpEA7Vjj7kcUdxMLXGyRKqT0ufinVpx2pAqMeXvM7BaIneoqJk6JRidsxc2HxI9qRcslrs6gcyI6x8qtJgVwlPJgmyodt/oSQC4astqmSoa6CIIP3lYgq/78jy/LxIDJt4d2bJGBMkEg=
